apiVersion: apps/v1
kind: Deployment
metadata:
  name: apollo-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apollo-server-worker
  template:
    metadata:
        labels:
            app: apollo-server-worker
    spec:
        containers:
        -   name: serverworker
            image: apolloserverworker
            env:
            -   name: ServiceBusConnectionKey
                value: 
            ports:
            -   containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apollo-server-worker
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: apollo-server-worker